#pragma once

#define DYNAMIC_KEYMAP_LAYER_COUNT 4
#define TAPPING_TERM 150
#define IGNORE_MOD_TAP_INTERRUPT
#define NO_AUTO_SHIFT_ALPHA
#define SPLIT_LAYER_STATE_ENABLE

#define ENABLE_RGB_MATRIX_ALPHAS_MODS
